# 配置详情请参考：https://docs.halo.run/zh/developer-guide/theme/config-files
genernal:
  label: 基本设置
  items:
    index_notice:
      name: index_notice
      label: 首页公告
      type: textarea
      default: '欢迎来到我的博客'
    icp:
      name: icp
      label: ICP 备案号
      type: text
      default: ""
      placeholder: "请填写 ICP 备案号信息"
      description: "ICP 备案信息将展示在页脚中，不填不展示（示例：鄂ICP备20001234号-1）"
    police:
      name: police
      label: 公网安备号
      type: text
      default: ""
      placeholder: "请填写公网安备号信息"
      description: "公网安备信息将展示在页脚中，不填不展示，也可在 “页脚” 一栏中单独关闭（示例：鄂公网安备42011102001234号）"
    site_notice:
      name: site_notice
      label: 网站公告
      type: textarea
      placeholder: 请输入公告信息
      description: "网站公告信息，将展示在页面右侧，尽量简洁明了（不填不展示该模块，也可单独开关）"
    baidu_statistic:
      name: baidu_statistic
      label: 统计代码
      type: textarea
      placeholder: 请输入统计代码
      description: "支持百度或其他平台统计代码（请自行生成），将插入 head 标签中（后台管理中也可设置，只需设置一处即可）"

